print("if it says true then first number is bigger")
print("if it says false then second number is bigger")
number1 = input("enter first number: ")
number2 = input("enter second number: ")
print(number1 > number2)